const assert=require('assert');
const {harness,seedCreature}=require('./smoke.cjs');
const make=(world={})=>harness(JSON.stringify(seedCreature({wait:100},world)));
const click=(h,id)=>h.el('buildings').onclick({target:{closest:()=>h.buildButton(id)}});
const key=(h,key)=>h.events.keydown({key,target:{tagName:'BUTTON'}});
for(const [type,reason] of [['bath','6个体'],['orchard','10个体'],['play','15个体'],['mine','50'],['factory','300'],['tower','16个体']]){
 const h=make();h.api.selectTool('harvest');h.el('open-build').click();const before=h.api.getState();
 for(let n=0;n<3;n++){click(h,type);assert.equal(h.api.interactionState().tool,'harvest');assert.equal(h.api.interactionState().building,null);assert.equal(h.el('detail-panel').hidden,false);assert(h.el('toast').textContent.includes(reason));assert.deepEqual(h.api.getState(),before)}
 const b=h.buildButton(type);assert(b.classList.contains('locked'));assert(!b.classList.contains('insufficient'));assert.equal(b.attributes['aria-disabled'],'true');assert.equal(b.disabled,false);
}
const poor=make({wood:3,gems:1,maxPopulation:10});poor.el('open-build').click();click(poor,'orchard');assert(poor.el('toast').textContent.includes('7木材、1晶石'));assert.equal(poor.api.interactionState().tool,'inspect');assert.equal(poor.el('detail-panel').hidden,false);assert(poor.buildButton('orchard').classList.contains('insufficient'));assert(!poor.buildButton('orchard').classList.contains('locked'));
assert.equal(poor.api.selectBuilding('orchard'),false,'direct entry is guarded');poor.api.selectTool('build');poor.api.actAt(9,10);assert.equal(poor.api.getState().buildings.length,0,'tool-only entry cannot bypass');
const preserve=make({wood:24,gems:12,maxPopulation:10});assert(preserve.api.selectBuilding('orchard'));preserve.el('open-build').click();click(preserve,'factory');assert.equal(preserve.api.interactionState().building,'orchard');assert.equal(preserve.el('detail-panel').hidden,false);click(preserve,'tower');assert.equal(preserve.api.interactionState().building,'orchard');
const preservePoor=make({wood:12,gems:4,maxPopulation:10});assert(preservePoor.api.selectBuilding('orchard'));click(preservePoor,'nest');assert.equal(preservePoor.api.interactionState().building,'orchard');assert(preservePoor.el('toast').textContent.includes('资源不足'));
const exact=make({wood:18,gems:5});click(exact,'nest');click(exact,'nest');assert.equal(exact.api.getState().wood,18,'selection never spends');assert(exact.buildButton('nest').classList.contains('active'));exact.api.actAt(9,10);exact.api.actAt(9,10);assert.equal(exact.api.getState().buildings.length,1);assert.equal(exact.api.getState().wood,0);assert.equal(exact.api.getState().gems,0);assert.equal(exact.api.interactionState().building,null);assert.equal(harness(exact.storage.value).api.getState().buildings.length,1);click(exact,'nest');assert.equal(exact.api.interactionState().tool,'inspect');
const race=make({wood:18,gems:5});race.api.selectBuilding('nest');assert(race.api.split());assert.equal(race.api.interactionState().building,'nest','no UI refresh yet');race.api.actAt(9,10);assert.equal(race.api.getState().wood,18);assert.equal(race.api.getState().gems,3);assert.equal(race.api.getState().buildings.length,0);assert.equal(race.api.interactionState().building,null);assert(race.el('toast').textContent.includes('已取消放置'));
const invalidated=make({wood:60,gems:5});invalidated.api.selectBuilding('nest');invalidated.el('bridge-build').click();assert.equal(invalidated.api.interactionState().tool,'inspect');assert.equal(invalidated.api.interactionState().building,null);assert(invalidated.buildButton('nest').classList.contains('insufficient'));
const replenish=make({wood:15,gems:5});click(replenish,'nest');replenish.api.selectTool('harvest');const tree=replenish.api.getState().objects.find(o=>o.type==='tree'&&o.x<22&&o.y>1);replenish.api.actAt(tree.x,tree.y);assert.equal(replenish.buildButton('nest').dataset.availability,'available');assert(replenish.api.selectBuilding('nest'));key(replenish,'5');assert.equal(replenish.api.interactionState().building,null);assert.equal(replenish.api.interactionState().tool,'harvest');replenish.api.selectBuilding('nest');key(replenish,'Escape');assert.equal(replenish.api.interactionState().tool,'inspect');
const unlock=make({wood:22,gems:45,maxGems:45,ore:5});assert.equal(unlock.api.buildAvailability('mine').state,'locked');unlock.el('process-ore').click();assert.equal(unlock.buildButton('mine').dataset.availability,'available');assert(unlock.api.selectBuilding('mine'));unlock.api.actAt(9,10);assert.equal(unlock.api.getState().wood,22);assert.equal(unlock.api.interactionState().building,'mine');unlock.api.actAt(7,15);assert.equal(unlock.api.getState().wood,0);
const historical=make({wood:100,gems:100,maxPopulation:16,maxGems:300});assert.equal(historical.api.buildAvailability('bath').state,'available');assert.equal(historical.api.buildAvailability('factory').state,'available');assert.equal(historical.api.buildAvailability('tower').state,'locked','tower requires living population');
const paused=make();paused.api.selectBuilding('nest');paused.el('pause').click();paused.api.actAt(9,10);assert.equal(paused.api.getState().buildings.length,0);assert.equal(paused.api.getState().wood,24);
console.log('PASS: construction button/DOM state, all unlocks, specific deficits, repeated clicks, preserved panel/tool/placement, direct-entry guard, exact-once charges/save, split race and bridge invalidation, resource/unlock transitions, keyboard cancel and pause');
