const assert=require('assert');
const {harness,seedCreature}=require('./smoke.cjs');
function seeded(changes={},world={}){return harness(JSON.stringify(seedCreature({x:10,y:10,tx:10,ty:10,wait:100,...changes},{ore:20,...world})));}
function pointer(h,x,y,id=1,extra={}){const p=h.api.worldPoint(x,y);return{clientX:p.x,clientY:p.y-15,pointerId:id,button:0,isPrimary:true,...extra};}
function dragTo(h,x,y,id=1){const c=h.api.getState().creatures[0],a=pointer(h,c.x,c.y,id),b=pointer(h,x,y,id);h.events.game.pointerdown(a);h.events.game.pointermove(b);return b;}
const h=seeded();let destination;
for(let x=8;x<15;x++)for(let y=6;y<15;y++)if(h.api.dropAllowed(x,y)&&Math.hypot(x-10,y-10)>1)destination={x,y};assert(destination);
let b=dragTo(h,destination.x,destination.y);assert.equal(h.api.interactionState().holding,1);h.api.advance(1);assert.equal(h.api.getState().creatures[0].x,10,'held creature frozen');assert.equal(h.api.interactionState().pan.x,0,'lifting does not pan');h.events.game.pointerup(b);let c=h.api.getState().creatures[0];assert(Math.abs(c.x-destination.x)<.001&&Math.abs(c.y-destination.y)<.001,'drop tracks world coordinates');assert(JSON.parse(h.storage.value).creatures[0].x===c.x,'drop persists');
for(const event of ['pointercancel','lostpointercapture']){const a=seeded();b=dragTo(a,destination.x,destination.y);a.events.game[event](b);assert.equal(a.api.interactionState().holding,null);assert.equal(a.api.getState().creatures[0].x,10)}
for(const end of ['outside','water','pause','tool','escape']){const a=seeded();b=dragTo(a,destination.x,destination.y);if(end==='outside')b.clientX=-100;if(end==='water')b=pointer(a,0,0);if(end==='pause')a.el('pause').click();if(end==='tool')a.api.selectTool('feed');if(end==='escape')a.events.keydown({key:'Escape',target:{tagName:'CANVAS'}});a.events.game.pointerup(b);assert.equal(a.api.getState().creatures[0].x,10,end+' restores origin')}
const multi=seeded();b=dragTo(multi,destination.x,destination.y);multi.events.game.pointerup({...b,pointerId:2});assert.equal(multi.api.interactionState().holding,1);multi.events.game.pointerup(b);
const tap=seeded();const tapP=pointer(tap,10,10);tap.events.game.pointerdown(tapP);tap.events.game.pointerup(tapP);assert.equal(tap.el('detail-panel').hidden,false,'tap selects');
for(const zoom of ['zoom-in','zoom-out']){const a=seeded();for(let i=0;i<3;i++)a.el(zoom).click();b=dragTo(a,destination.x,destination.y);a.events.game.pointerup(b);assert(Math.abs(a.api.getState().creatures[0].x-destination.x)<.001,zoom+' coordinates')}
const pan=seeded();pan.api.selectTool('pan');b=dragTo(pan,11,10);pan.events.game.pointerup(b);assert(pan.api.interactionState().pan.x!==0);assert.equal(pan.api.getState().creatures[0].x,10);
const shot=seeded();shot.api.selectTool('throw');const p=pointer(shot,10,10);shot.events.game.pointerdown(p);shot.events.game.pointerup(p);assert.equal(shot.api.getState().ore,19);assert.equal(shot.api.getState().creatures[0].health,100,'impact deferred');shot.api.advance(.5);assert(shot.api.getState().creatures[0].health<83);assert.equal(shot.api.getState().creatures[0].behavior,'stunned');assert.equal(shot.api.interactionState().shots,0);shot.api.advance(.1);shot.api.actAt(10,10);shot.api.actAt(10,10);assert.equal(shot.api.getState().ore,18,'repeat cooldown');shot.api.advance(.5);
const noOre=seeded({}, {ore:0});noOre.api.selectTool('throw');noOre.api.actAt(10,10);assert.equal(noOre.api.interactionState().shots,0);assert(noOre.el('toast').textContent.includes('3矿石'));
const noDamage=seeded();noDamage.api.selectTool('throw');noDamage.el('pause').click();noDamage.api.actAt(10,10);assert.equal(noDamage.api.getState().ore,20);noDamage.el('pause').click();b=dragTo(noDamage,11,10);noDamage.events.game.pointerup(b);assert.equal(noDamage.api.getState().ore,20,'drag never throws');
const buildSeed=seedCreature({x:10,y:10,tx:10,ty:10,wait:100},{ore:20});buildSeed.buildings=[{x:14,y:10,type:'nest',t:0}];buildSeed.objects=buildSeed.objects.filter(o=>o.x!==14||o.y!==10);const building=harness(JSON.stringify(buildSeed));building.api.selectTool('throw');for(let i=0;i<4;i++){building.api.actAt(14,10);building.api.advance(.6)}assert.equal(building.api.getState().buildings.length,0,'four impacts destroy facility');assert.equal(building.api.getState().wood,24,'destruction grants no resources');
const obj=seeded();const target=obj.api.getState().objects.find(o=>o.type==='rock'&&o.x<20&&o.y>1);obj.api.selectTool('throw');obj.api.actAt(target.x,target.y);obj.api.advance(.6);assert.equal(obj.api.getState().objects.find(o=>o.x===target.x&&o.y===target.y).amount,5,'rock destruction reduces resource stock');obj.api.advance(25);assert(obj.api.getState().objects.find(o=>o.x===target.x&&o.y===target.y).amount>5,'resources regrow');
const persisted=harness(building.storage.value);assert.equal(persisted.api.getState().buildings.length,0);
if(process.env.INTERACTION_SCREENSHOT){const v=seeded();dragTo(v,destination.x,destination.y);v.frame(1000);require('fs').writeFileSync(process.env.INTERACTION_SCREENSHOT,v.el('game').canvas.toBuffer('image/png'));}
console.log('PASS: tap, pickup, valid/invalid/outside drops, touch pointer ownership, cancellation/lost capture, pause/Escape/tool cancellation, pan separation, zoom, persistence, delayed stone hits/cooldown/cost, no-ore feedback, building destruction and regrowth');
