const fs=require('fs'),vm=require('vm'),assert=require('assert');
let createCanvas;try{({createCanvas}=require('@napi-rs/canvas'))}catch{}
const source=fs.readFileSync(require('path').join(__dirname,'../dist/game.js'),'utf8');
function harness(saved){let events={},frame;const storage={value:saved,getItem(){return this.value},setItem(k,v){this.value=v}};const noop=()=>{};const fakeContext=new Proxy({},{get:()=>noop,set:()=>true});const elements=new Map();function el(id){if(elements.has(id))return elements.get(id);let canvas=createCanvas&&['game','portrait'].includes(id)?createCanvas(id==='game'?1120:120,id==='game'?680:100):null;let o={id,style:{},dataset:{},classList:{add:noop,remove:noop,toggle:noop},addEventListener(n,f){(events[id]??={})[n]=f},setAttribute:noop,getBoundingClientRect:()=>({width:1120,height:680,left:0,top:0}),getContext:()=>canvas?canvas.getContext('2d'):fakeContext,setPointerCapture:noop,showModal(){this.open=true},close(){this.open=false},click(){this.onclick?.()},get width(){return canvas?.width},set width(v){if(canvas)canvas.width=v},get height(){return canvas?.height},set height(v){if(canvas)canvas.height=v},canvas};elements.set(id,o);return o}const doc={getElementById:el,querySelector:()=>null,querySelectorAll:()=>[],addEventListener:noop,hidden:false};const context={document:doc,window:{addEventListener:noop},localStorage:storage,ResizeObserver:class{observe(){}},requestAnimationFrame:f=>frame=f,clearTimeout:noop,setTimeout:noop,console,Math,Set};vm.createContext(context);vm.runInContext(source,context);return {api:context.window.Thronglets,el,events,storage,frame:t=>frame(t)}}
const h=harness(),g=h.api;let a=g.getState();assert.equal(a.creatures.length,1);g.selectTool('feed');g.actAt(10.2,11);assert.equal(g.getState().food,28);assert(g.getState().creatures[0].food>95);g.selectTool('play');g.actAt(10.2,11);assert(g.split());assert.equal(g.getState().creatures.length,2);
a=g.getState();let tree=a.objects.find(o=>o.type==='tree'),rock=a.objects.find(o=>o.type==='rock');g.selectTool('harvest');g.actAt(tree.x,tree.y);assert.equal(g.getState().wood,a.wood+3);g.actAt(rock.x,rock.y);assert.equal(g.getState().gems,a.gems+2);
function build(type,x,y){h.el('buildings').onclick({target:{closest:()=>({dataset:{build:type}})}});g.actAt(x,y)}
build('orchard',9,10);assert.equal(g.getState().buildings.length,1);let old=g.getState().wood;build('bath',9,10);assert.equal(g.getState().wood,old,'occupied tile must not spend');build('tower',8,10);assert.equal(g.getState().buildings.length,1,'tower must lock below 16');g.advance(12);assert(g.getState().food>12);h.el('pause').click();assert(g.paused);h.el('pause').click();assert(!g.paused);h.el('speed').click();assert.equal(g.speed,2);h.el('speed').click();assert.equal(g.speed,4);h.el('speed').click();assert.equal(g.speed,1);
h.frame(1000);if(h.el('game').canvas&&process.env.GAME_SCREENSHOT)fs.writeFileSync(process.env.GAME_SCREENSHOT,h.el('game').canvas.toBuffer('image/png'));h.el('confirm-reset').click();assert.equal(g.getState().creatures.length,1);assert(h.storage.value);const restored=harness(h.storage.value);assert.equal(restored.api.getState().creatures.length,1);
// Stress the simulation and natural reproduction with an explicitly seeded local test save.
let seeded=g.getState();seeded.food=500;seeded.wood=500;seeded.gems=500;seeded.creatures[0].food=100;seeded.creatures[0].clean=100;seeded.creatures[0].happy=100;seeded.buildings=[{type:'orchard',x:9,y:10,t:0},{type:'bath',x:10,y:10,t:0},{type:'play',x:11,y:10,t:0},{type:'nest',x:12,y:11,t:0},{type:'nest',x:12,y:12,t:0},{type:'mine',x:13,y:12,t:0}];const stress=harness(JSON.stringify(seeded));stress.api.advance(300);const st=stress.api.getState();assert(st.creatures.length>1,'natural reproduction');assert(st.creatures.every(c=>Number.isFinite(c.x)&&c.health>0));assert(st.gems>450,'mine produces gems');assert(st.creatures.length<=24);console.log('PASS: care, split, harvest, costs, occupied placement, tower unlock, orchard production, pause, speed, reset, local persistence, autonomous care/reproduction, 300 simulated seconds');console.log('Stress population',st.creatures.length,'buildings',st.buildings.length);
